It works.
learningequality/sushi-chef-better-world-ed pull request #2
Opened 2017-11-09 22:21 UTC by danflorencio

Sushi chef is working, just need to clean up code.

2017-11-09 23:45 UTC, jayoshih requested changes
Awesome work! Overall, just a matter of removing commented out code, adding comments on certain parts of the code, and removing any extraneous files

2017-11-09 23:45 UTC, jayoshih commented on bwe_overall_database.csv
> +Grade Level Range,Math Topic,Specific Objective,Written Story,Video,Lesson Plan,BWE Topic
Probably best to not commit this

2017-11-09 23:45 UTC, jayoshih commented on client_secret.json
> +{"web":{"client_id":"417180537270-fkp5muapn4psf0nrn9kuod3dvlalc59r.apps.googleusercontent.com","project_id":"dark-hall-182220","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"http
Probably don't want to commit this as it might contain sensitive information (we can upload this file manually)

2017-11-09 23:45 UTC, jayoshih commented on client_secrets.json
> +{"web":{"client_id":"281462459770-3qbgdmi60245nsg19fnqb8bu0l7v09ak.apps.googleusercontent.com","project_id":"fresh-booster-185501","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"
Same as above

2017-11-09 23:45 UTC, jayoshih commented on souschef.py
> +fields = []
Does these need to be global variables?

2017-11-09 23:45 UTC, jayoshih commented on souschef.py
> +        Better World Ed is organized with the following hierarchy:
Nice, very clear and super useful for continued maintenance!

2017-11-09 23:45 UTC, jayoshih commented on souschef.py
> +		2)
Can remove this note, but maybe also add a note that you've updated the downloader function as `add_file` doesn't account for downloading from google

2017-11-09 23:45 UTC, jayoshih commented on souschef.py
> +	#docsRegex = re.search(r'https://docs\.google\.com/document/./([^/]*)', path)
Remove comment

2017-11-09 23:45 UTC, jayoshih commented on sushichef.py
> +# OPEN STAX LINE COOK
Rename to BetterWorldEdChef to avoid confusion

2017-11-09 23:45 UTC, jayoshih commented on utils/downloader.py
> +#import comtypes
Remove comment

2017-11-09 23:45 UTC, jayoshih commented on requirements.txt
> +youtube-dl
Also need to add `pydrive==1.3.1`

2017-11-09 23:45 UTC, jayoshih commented on souschef.py
> +			#print ("loop")
Remove comment

2017-11-09 23:45 UTC, jayoshih commented on souschef.py
> +				gradeLevel = "Uncategorized"
Change "Uncategorized" to "Other"

2017-11-09 23:45 UTC, jayoshih commented on souschef.py
> +	# TODO: Replace line with scraping code
Remove

2017-11-09 23:45 UTC, jayoshih commented on utils/downloader.py
> +gauth = GoogleAuth()
Make all caps to make it clear these are constants, also might be good to add a comment on what they're used for

2017-11-09 23:45 UTC, jayoshih commented on utils/downloader.py
> +        if vimeo in path:
Can just use `if "vimeo.com" in path` to avoid need for variable

2017-11-09 23:45 UTC, jayoshih commented on utils/googleDrive.py
> +
Don't think we use this anymore? If not, can just remove this file

2017-11-09 23:45 UTC, jayoshih commented on utils/quickstart.py
> +from pydrive.auth import GoogleAuth
Don't think this is used either

2017-11-09 23:45 UTC, jayoshih commented on souschef.py
> +			try:
Could you add comments explaining what the following lines are doing?

2017-11-09 23:45 UTC, jayoshih commented on souschef.py
> +			print ("PATH: " + str(PATH))
Good to remove print statements for debugging

2017-11-09 23:45 UTC, jayoshih commented on souschef.py
> +				writer.add_file(str(PATH), title, "https://docs.google.com/document/d/1s-5q5TfAj_OeiQjHzDL0a90q0NO_gEq9eZnF8TkeLdU/edit?usp=sharing", ext=".pdf", license=licenses.CC_BY, copyright_holder="betterw
This seems to be resolved, so can switch back to older `add_file` method

2017-11-10 22:06 UTC, ivanistheone commented
@danflorencio  You should consider using [csv.DictReader](https://docs.python.org/2/library/csv.html#csv.DictReader) to go through the rows: slightly nicer dictionary-based interface instead of using indices 0,1,2.

2017-11-14 03:08 UTC, closed without merging